# Generated by Django 3.1.7 on 2021-03-21 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_number', models.CharField(default='51302', max_length=10, unique=True)),
                ('Story_Headline', models.CharField(max_length=64)),
                ('Story_Category', models.CharField(choices=[('pol', 'politics'), ('art', 'art_news'), ('tech', 'technology_new'), ('trivia', 'trivial_news')], default='trivia', max_length=6)),
                ('Story_Region', models.CharField(choices=[('uk', 'United_Kingdom_news'), ('eu', 'European_news'), ('w', 'world_news')], default='uk', max_length=2)),
                ('Post_Date', models.DateTimeField(auto_now_add=True)),
                ('Story_Details', models.CharField(max_length=512)),
                ('Authors', models.ManyToManyField(to='story.Author')),
            ],
        ),
    ]
