# Generated by Django 3.1.7 on 2021-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210322_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Reference_number',
            field=models.CharField(default='24424', max_length=10, unique=True),
        ),
    ]
