# Generated by Django 3.1.7 on 2021-03-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20210322_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='Reference_number',
        ),
    ]
